[package]
name = "pyrage"
version = "1.4.0"
edition = "2021"
description = "Python bindings for rage (age in Rust)"
readme = "README.md"
homepage = "https://github.com/woodruffw/pyrage"
repository = "https://github.com/woodruffw/pyrage"
license = "MIT"

[package.metadata.release]
publish = false  # handled by GitHub Actions
push = true

[lib]
crate-type = ["cdylib"]

[dependencies]
age = { version = "0.12.1", features = ["armor", "plugin", "ssh"] }
age-core = "0.12"
pyo3 = {
  version = "0.24.2",
  features = [
    "abi3",
    "abi3-py310",
    "extension-module",
    "py-clone",
  ]
}
pyo3-file = "0.12.0"
