from typing import Optional

def encrypt(plaintext: bytes, passphrase: str, armored: bool = False) -> bytes: ...
def decrypt(
    ciphertext: bytes, passphrase: str, max_work_factor: Optional[int] = None
) -> bytes: ...
